# Generated by Django 4.0.5 on 2022-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_keeper', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional')], default='Professional', max_length=12),
        ),
    ]
