# Generated by Django 4.0.5 on 2022-08-05 19:11

import contact_keeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_keeper', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=contact_keeper.models.CustomPhoneField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
